name: Scheduled Azure VM Resize

on:
  schedule:
    - cron: '15 5 * * *'   # up_cron: resize up (e.g., change VM size to Standard_D4s_v3)
    - cron: '30 5 * * *'   # down_cron: resize down

jobs:
  resize-vm-up:
    if: github.event_name == 'schedule' && contains(join(github.event.schedule, ','), '15 5 * * *')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Cache Python virtual environment
        uses: actions/cache@v4
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}

      - name: Set up Python virtual environment and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      # resize.py expects RESIZE_ACTION to be set to 'up' or 'down' to determine the resize direction
      - name: Decide resize action and update tfvars (up)
        env:
          RESIZE_ACTION: up
        run: python resize.py
        run: pip install pyyaml

      - name: Decide resize action and update tfvars (up)
        env:
          RESIZE_ACTION: up
        run: python resize.py

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  resize-vm-down:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is the down_cron schedule
        id: check_cron
        run: |
          if [[ "${{ github.event.schedule }}" != "30 5 * * *" ]]; then
            echo "Not the down_cron schedule, skipping job."
            exit 78
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # resize.py expects RESIZE_ACTION to be set to 'up' or 'down' to determine the resize direction
      - name: Decide resize action and update tfvars (down)
        env:
          RESIZE_ACTION: down
        run: python resize.py
          pip install pyyaml

      - name: Decide resize action and update tfvars (down)
        env:
          RESIZE_ACTION: down
        run: python resize.py

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
