name: Scheduled Azure VM Resize

on:
  schedule:
    - cron: '25 18 * * *'   # up_cron: resize up
    - cron: '35 18 * * *'  # down_cron: resize down
  workflow_dispatch:
jobs:
  resize-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Python dependencies
        run: pip install pyyaml

      - name: Decide resize action and update tfvars
        env:
          SCHEDULE_CRON: ${{ github.event.schedule }}
        run: python resize.py
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
